### ISSUE TITLE
Undefined array key "amount"

### ISSUE THREAD

**Issue by LordFit** [Hebbinkpro/MagicCrates#14]
[Server thread/CRITICAL]: ErrorException: "Undefined array key "amount"" (EXCEPTION) in "plugins/MagicCrates-main/src/Hebbinkpro/MagicCrates/crate/CrateReward" at line 43
--- Stack trace ---
  #0 plugins/MagicCrates-main/src/Hebbinkpro/MagicCrates/crate/CrateReward(43): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[28] Undefined array key "amount", string[88] /root/survival/plugins/MagicCrates-main/src/Hebbinkpro/MagicCrates/crate/CrateRe, int 43)
  #1 plugins/MagicCrates-main/src/Hebbinkpro/MagicCrates/crate/CrateType(53): Hebbinkpro\MagicCrates\crate\CrateReward::decode(array[3])
  #2 plugins/MagicCrates-main/src/Hebbinkpro/MagicCrates/MagicCrates(64): Hebbinkpro\MagicCrates\crate\CrateType::decode(string[5] check, array[2])
  #3 plugins/MagicCrates-main/src/Hebbinkpro/MagicCrates/MagicCrates(48): Hebbinkpro\MagicCrates\MagicCrates->loadAllCrates()

**Comment by Hebbinkpro** [comment]
This is an issue caused by your `config.yml`.
I think you forgot to add the amount of the reward to one of your crates.

A reward has to look something like:
```yml
      - name: "Dirt" 
         item: 
           id: "minecraft:dirt" 
           amount: 2 
         commands: [ ] 
         amount: 2
```

If you cannot figure out how to fix the issue, please send your `config.yml`.
