### ISSUE TITLE
Issues with setting up new crate types

### ISSUE THREAD

**Issue by jsn4ev3r** [Hebbinkpro/MagicCrates#21]
Hi I Am having issues Ettington up new crate types can you show me an example of what it would look like to get 2 or more crate types to appear on the drop down menu

**Comment by Hebbinkpro** [comment]
Look in the README for an explanation.

Here is the example:
```yml
types:
  common:
    name: "§eCommon §6Crate"
    rewards:
      - name: "Dirt"
        item:
          id: "minecraft:dirt"
          name: "Dirt"
          amount: 1
  rare:
    name: "§eRare §6Crate"
    rewards:
      - name: "Diamond"
        item:
          id: "minecraft:diamond"
          name: "Diamond"
          amount: 1
```
